# Generated by Django 4.2.14 on 2024-08-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Signup",
        ),
    ]
