# Generated by Django 4.2.14 on 2024-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_app", "0002_rename_user_signup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="signup",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="signup",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
